data_path: './Dataset/'
dataset: 'bundle'
search_depth: 2 # 2 before
train_num: 50

#Expand parameterwo
batch_size: 16
error_batch_size: 16
num_feedbacks: 3
steps_per_gradient: 1
addition_sample: 2
num_candidates: 8

#Select parameter
beam_width: 5 # 5 before
time_steps: 16 # 16 before
explore_param: 2 
sample_num: 32

#Reward
reward_func: 'rmse' #ndcg

#Wandb parameter
use_wandb: True
wandb_api_key: ''

# Evaluate
metrics: ["rmse"] #["hit","map","ndcg"]
model: "gpt-4o-mini"
seed: 42
candidate_size: 20 # double check we might not have any candidates (useless argument)
